MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'densenet161'
        PRETRAINED: True
        OUT_CHANNELS: [256,896,1920]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[18, 18], [9, 9], [9, 9],]
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val",)
SOLVER:
    MAX_ITER: 8000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/rdd2020_densenet161'
DATASET_DIR: "/work/datasets"
EVAL_STEP: 2000