MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnext50_800x450'
        PRETRAINED: False
        OUT_CHANNELS: [256,512,512,512,1024,1024]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[29, 50],[15,25], [8,13],[4,7],[2,4], [1,3]]
        STRIDES: [[28, 9], [54, 18], [100, 35], [200, 65], [400, 113], [800, 150]] #[[8, 8], [16, 16], [32, 32], [64, 64], [100, 100], [300, 300]]
INPUT:
    IMAGE_SIZE: [800, 450]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val",)
SOLVER:
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/rdd2020_resnext50_800x450_server'
DATASET_DIR: "datasets"
EVAL_STEP: 2000
MODEL_SAVE_STEP:  1000