MODEL:
    NUM_CLASSES: 11
    THRESHOLD : 0.6
    PRIORS:
        MIN_SIZES : [[20, 20], [40, 40], [111, 111], [162, 162], [213, 213], [264, 264]]
        MAX_SIZES : [[60, 60], [111, 111], [162, 162], [213, 213], [264, 264], [315, 315]]
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: False
        OUT_CHANNELS: [128, 256, 128, 128, 64, 64]
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("mnist_detection_train", "mnist_detection_val")
    TEST: ("mnist_detection_val", )
SOLVER:
    MAX_ITER: 15000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 2e-3
OUTPUT_DIR: 'outputs/basic'
DATASET_DIR: "/work/datasets"