MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet50_600x600'
        PRETRAINED: False
        OUT_CHANNELS: [1024,2048,1024,1024,1024,1024]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[38, 38],[19,19], [10,10],[5,5],[3,3], [1,1]]
        STRIDES: [[16, 16], [32, 32], [60, 60], [120, 120], [200, 200], [600, 600]] #[[8, 8], [16, 16], [32, 32], [64, 64], [100, 100], [300, 300]]
INPUT:
    IMAGE_SIZE: [600, 600]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val",)
SOLVER:
    MAX_ITER: 120000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/rdd2020_resnet50_600x600'
DATASET_DIR: "/work/datasets"
EVAL_STEP: 2000
MODEL_SAVE_STEP:  2000
